# Generated by Django 4.0.3 on 2022-06-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
